name: stage flavour
favicon: null
layout_spectrum: 0.44509
typography_spectrum: 0.41804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdffff'
    - '#9d9f9e'
    - '#07090a'
    - '#ea1f16'
    - '#057841'
  brandStrength: 0
  lightness: 0.8046221602708101
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
