name: stage flavour
favicon: null
layout_spectrum: 0.10566604067571461
typography_spectrum: 0.9825887868646532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8466286342591047
  lightness: 0.8046221602708101
  saturation: 0.37295910716056824
  rhythmicContrast: 0.605826566927135
purpose: []
